spring.application.name=social-media-planner

spring.datasource.url=jdbc:postgresql://localhost:5432/post_scheduler_db
spring.datasource.username=postgres
spring.datasource.password=Password
spring.jpa.hibernate.ddl-auto=update

server.port=8081

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.chat.id=${TELEGRAM_CHAT_ID}

linkedin.access.token=${LINKEDIN_ACCESS_TOKEN}
linkedin.person.urn=${LINKEDIN_PERSON_URN}