spring.application.name=social-media-planner

spring.datasource.url=jdbc:postgresql://localhost:5432/post_scheduler_db
spring.datasource.username=postgres
spring.datasource.password=Password
spring.jpa.hibernate.ddl-auto=update

server.port=8081

telegram.bot.token=8928197239:AAFQaH2Fp-nf0xaZpJUn1vlsJVY5rp4dnTA
telegram.chat.id=7406964373